name: CI

on:
  workflow_call:
# on:
#   push:
#     # branches: [ "main" ]
#     tags:
#       - 'v*.*.*'
#   workflow_dispatch:

jobs:
  setenv:
    runs-on: cluster0-nxcp-runner
    needs: build
    steps:
      - name: Check Tag
        id: check-tag
        run: |
          if [[ $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              echo ::set-output name=match::true;
          else
              exit 1;
          fi
      - name: Check ENV
        id: getenv
        run: |
          eval $(curl github-secret.github-action-secret.svc:8080/secret);
          echo "::set-output name=harbor_registry::$HARBOR_REGISTRY"
          echo "::set-output name=harbor_user::$HARBOR_USER"
          echo "::set-output name=harbor_pass::$HARBOR_PASS"
          echo "::set-output name=tag_name::${GITHUB_REF_NAME:1}"
      - uses: actions/checkout@v3
    outputs:
      harbor_registry: ${{ steps.getenv.outputs.harbor_registry }}
      harbor_user: ${{ steps.getenv.outputs.harbor_user }}
      harbor_pass: ${{ steps.getenv.outputs.harbor_pass }}
      tag_name: ${{ steps.getenv.outputs.tag_name }}